### ISSUE TITLE
Option: ignore values

### ISSUE THREAD

**Issue by matamadio** [MamadioCMCC/HazardRiskScripts#10]
Most ofthen than not, raster files show NoData as the most weird values; and most ofthen than not, this value is not specified as "NoData" in the file metadata.
To solve that, one requires to fix the value and resave each tif; whereas it would be nice to just ignore identified nodata values in the stats through command line.
e.g.
--ignore -99999, 99999, 15

**Comment by ConnectedSystems** [comment]
Submitted a PR to address this, but should be noted that this should only be used for one-off cases.

Ignoring values on rasters that will be used a lot is not good practice. Such rasters should have the proper metadata set.
