### ISSUE TITLE
Ignore arg cannot be removed

### ISSUE THREAD

**Issue by matamadio** [MamadioCMCC/HazardRiskScripts#16]
It is just a minor issue, basically you cannot leave argument --ignore out when you don't have values to ignore, you have to specify --ignore ""

**Comment by ConnectedSystems** [comment]
I guess the question here then is which is the safer approach.

Do we enforce explicit "nothing to ignore" which can be annoying but protects users who accidentally forget to include their ignore values which would lead to weird results...

**Comment by matamadio** [comment]
Ye, I can just specify it is a mandatory arg in the readme.
