### ISSUE TITLE
Not working on a new dataset

### ISSUE THREAD

**Issue by matamadio** [MamadioCMCC/HazardRiskScripts#17]
Today I was trying on a new set of data but I got a new error:

![immagine](https://user-images.githubusercontent.com/44863827/84483935-53daa300-ac9a-11ea-8b74-07461294f713.png)

EPSG is both 3044 and incorrect geometries were removed from shapefile.

Test data is [here](https://drive.google.com/file/d/1rmemOXTXBHKN7KOFkdftXjC1fYyBHlHu/view?usp=sharing)

**Comment by matamadio** [comment]
As far as I understood from error search, it seems to be a problem with the way multiprocessing is processed.
https://bugs.python.org/issue9733
https://github.com/unbit/uwsgi/issues/206

**Comment by matamadio** [comment]
Nope, it is not multiprocessing, as it fails also using --cores 1
It seems it don't recognise the crs properly. I'll try to reproject.

Traceback (most recent call last):
  File "runstats.py", line 145, in <module>
    main(output_fn, **opts)
  File "runstats.py", line 83, in main
    results = extract_stats(shp_fns, rst_fns, field, stats, ignore, preprocess)
  File "D:\Amadio\Rimini_ANUGA\hazardstat.py", line 238, in extract_stats
    crs_matches, issue = matching_crs(ds, shp)
  File "D:\Amadio\Rimini_ANUGA\hazardstat.py", line 143, in matching_crs
    shp_str = shp_data.crs['init']
KeyError: 'init'

**Comment by ConnectedSystems** [comment]
I'll have a look soon. At first glance the issues you linked to appear to be resolved so I suspect it's something else...

**Comment by matamadio** [comment]
It was a crs problem of source data. Closing.
